### ISSUE TITLE
Getting HostObject::get error

### ISSUE THREAD

**Issue by dachinat** [react-native-community/react-native-device-info#619]
## Summary

I followed instructions with automatic linking. It builds correctly.

|             |     |
| ----------- | --- |
| Version     | Latest   |
| Affected OS | Android  |
| OS Version  | Pie   |

## Current behavior

I'm getting:

> Exception in HostObject::get: < unknown >
> <unknown>
> deviceinfo.js:6:33
>
> loadModuleImplementation
> require.js:331:6
> ...

when I use
 
```js
console.log('-->', DeviceInfo.getUniqueID());
```

## Expected behavior

I should get device id in console.

**Comment by dachinat** [comment]
<img width="646" alt="Screen Shot 2019-04-02 at 4 19 07 PM" src="https://user-images.githubusercontent.com/22872749/55401901-2442ed80-5563-11e9-9561-2bdac1cac0c7.png">

This solved this.

**Comment by mikehardy** [comment]
You will be very unhappy with that change in the long run. Examine the example/app/build.gradle file for the ext block and how version pinning/synchronization between modules is done as a best practice...

**Comment by mcgloneleviROOT** [comment]
Several colleagues and I just spent 16+ hours debugging this issue.  Here was our fix for this in case anyone else runs into this.

Inside build.gradle
```
project.ext {
    .....other entries...
    googlePlayServicesVersion = '16.1.0'
}

configurations.all {
         resolutionStrategy {
            .......other entries........
            force 'com.google.android.gms:play-services-gcm:16.1.0'
        }
}
```

**Comment by mikehardy** [comment]
Hmm - @mcgloneleviROOT very sorry to hear about the lost time, but note that you did not use your ext variable in your resolutionStrategy :thinking: 

Also, I continue to believe the presence of a resolutionStrategy indicates some structural problem that should be fixed, and resolutionStrategy is just forcibly covering it up - but I also recognize that there are a limitless number of ways to build software and I am sure a few justify the use of resolutionStrategy like this. Which is to say - I would put a FIXME in that block if it were me, and I would review it everyone month or two to see if I could clean things up and still build

Good luck!

**Comment by dachinat** [comment]
@mcgloneleviROOT You're best, thanks

**Comment by enaluz** [comment]
I'm still getting this issue on iOS. Does anyone have any ideas on what may be causing this?
